#ifndef __HEADER_H__
#define __HEADER_H__

#define CONFIG_USE_SICK_SENSOR 
#define CONFIG_USE_FILE_SYSTEM
#define CONFIG_USE_NPT_TIME 
#define CONFIG_USE_MODBUS_RTU
#define CONFIG_USE_MODBUS_TCP
#define CONFIG_USE_MQTT 

#endif //__HEADER_H__
